import {createWorker} from 'tesseract.js';
import * as pdfjs from 'pdfjs-dist';
import {Document,Packer,Paragraph,TextRun} from 'docx';
import {PDFDocument} from 'pdf-lib';
const asset = path => new URL(path, import.meta.url).href;
pdfjs.GlobalWorkerOptions.workerSrc=asset('vendor/pdf.worker.mjs');
const $=id=>document.getElementById(id);let mode='ocr',file=null,busy=false,worker=null,cancelled=false,previewURL=null;
const status=(s,error=false)=>{$('status').textContent=s;$('status').classList.toggle('error',error)};
function reset(){ $('result').hidden=true;$('text').value='';$('progress').hidden=true; }
function setMode(m){if(busy)throw Error('Өңдеу аяқталғанша күте тұр.');if(!['ocr','image','pdf'].includes(m))throw Error('Белгісіз режим');mode=m;reset();document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));for(const k of ['ocr','image','pdf'])$(k+'Options').hidden=k!==m;$('convert').textContent=m==='ocr'?'Мәтінді тану ↗':'Конвертациялау ↗';$('file').accept=m==='ocr'?'image/png,image/jpeg,image/webp,application/pdf':'image/png,image/jpeg,image/webp';$('formats').textContent=m==='ocr'?'PNG, JPEG, WebP, PDF · 20 МБ дейін':'PNG, JPEG, WebP · 20 МБ дейін';if(file?.type==='application/pdf'&&m!=='ocr'){file=null;$('selected').hidden=true;$('file').value='';}$('convert').disabled=!file;status(file?'Файл дайын.':'Алдымен файлды таңда.');return {mode};}
function choose(f){if(busy||!f)return;reset();file=null;$('convert').disabled=true;$('selected').hidden=true;$('preview').hidden=true;if(previewURL)URL.revokeObjectURL(previewURL);if(f.size>20*1024*1024)return status('Файл 20 МБ-тан аспауы тиіс.',true);if(!f.size)return status('Файл бос.',true);if(!['image/png','image/jpeg','image/webp',...(mode==='ocr'?['application/pdf']:[])].includes(f.type))return status('Қолдау көрсетілмейтін формат. PNG, JPEG, WebP немесе PDF таңда.',true);file=f;$('filename').textContent=f.name;$('filesize').textContent=(f.size/1048576).toFixed(2)+' МБ';$('selected').hidden=false;if(f.type.startsWith('image/')){$('preview').src=previewURL=URL.createObjectURL(f);$('preview').hidden=false;}$('convert').disabled=false;status('Файл дайын.');}
async function canvasOf(f){const bmp=await createImageBitmap(f);if(bmp.width*bmp.height>40000000){bmp.close();throw Error('Сурет тым үлкен. 40 мегапиксельден кіші нұсқасын таңда.');}const scale=Math.min(1,3000/Math.max(bmp.width,bmp.height));const c=document.createElement('canvas');c.width=Math.round(bmp.width*scale);c.height=Math.round(bmp.height*scale);const ctx=c.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(bmp,0,0,c.width,c.height);bmp.close();return c;}
const blobOf=(c,type)=>new Promise((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(Error('Суретті сақтау мүмкін болмады.')),type,.92));
function download(blob,ext){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=(file?.name.replace(/\.[^.]+$/,'')||'document')+'.'+ext;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}
async function recognize(c){if(cancelled)throw Error('Тоқтатылды.');if(!worker)worker=await createWorker($('lang').value,1,{workerPath:asset('vendor/worker.min.js'),corePath:asset('vendor/core'),langPath:asset('vendor/lang'),logger:m=>{if(m.status==='recognizing text')$('progress').value=m.progress;},errorHandler:()=>{}});if(cancelled)throw Error('Тоқтатылды.');return (await worker.recognize(c)).data.text;}
async function run(){if(!file||busy)return;busy=true;cancelled=false;reset();$('convert').disabled=true;$('cancel').hidden=false;document.querySelectorAll('nav button,select,input').forEach(e=>e.disabled=true);$('progress').hidden=false;status('Өңделуде… Алғашқы мәтін тану біраз уақыт алуы мүмкін.');let pdf,loading;
try{if(mode==='image'){const bmp=await createImageBitmap(file);if(bmp.width*bmp.height>40000000){bmp.close();throw Error('Сурет тым үлкен: шегі 40 мегапиксель.');}const c=document.createElement('canvas');c.width=bmp.width;c.height=bmp.height;const ctx=c.getContext('2d');if($('format').value==='jpeg'){ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);}ctx.drawImage(bmp,0,0);bmp.close();const b=await blobOf(c,'image/'+$('format').value);if(b.type!=='image/'+$('format').value)throw Error('Бұл браузер таңдалған форматты қолдамайды.');if(!cancelled)download(b,$('format').value==='jpeg'?'jpg':$('format').value);
}else if(mode==='pdf'){const c=await canvasOf(file),p=await PDFDocument.create(),img=await p.embedJpg(await (await blobOf(c,'image/jpeg')).arrayBuffer());const scale=Math.min(595/c.width,842/c.height),page=p.addPage([c.width*scale,c.height*scale]);page.drawImage(img,{x:0,y:0,width:page.getWidth(),height:page.getHeight()});if(!cancelled)download(new Blob([await p.save()],{type:'application/pdf'}),'pdf');
}else{let out=[];if(file.type==='application/pdf'){loading=pdfjs.getDocument({data:await file.arrayBuffer(),cMapUrl:asset('vendor/cmaps/'),cMapPacked:true,standardFontDataUrl:asset('vendor/standard_fonts/'),wasmUrl:asset('vendor/wasm/')});pdf=await loading.promise;if(pdf.numPages>30)throw Error('Бір ретте 30 бетке дейін. PDF-ті бөліп жүкте.');for(let i=1;i<=pdf.numPages;i++){if(cancelled)throw Error('Тоқтатылды.');status(i+' / '+pdf.numPages+' бет өңделуде…');const page=await pdf.getPage(i),content=await page.getTextContent();let txt=content.items.map(x=>x.str+(x.hasEOL?'\n':' ')).join('');if(txt.trim().length<5){const v=page.getViewport({scale:1}),vp=page.getViewport({scale:Math.min(2,3000/Math.max(v.width,v.height))}),c=document.createElement('canvas');c.width=Math.ceil(vp.width);c.height=Math.ceil(vp.height);await page.render({canvasContext:c.getContext('2d'),viewport:vp}).promise;txt=await recognize(c);c.width=c.height=0;}out.push(txt);page.cleanup();}}else out=[await recognize(await canvasOf(file))];if(cancelled)throw Error('Тоқтатылды.');const txt=out.join('\n\n');if(!txt.trim())throw Error('Мәтін табылмады. Анығырақ фото қолданып көр.');$('text').value=txt;$('result').hidden=false;}
if(cancelled)throw Error('Тоқтатылды.');$('progress').value=1;status(mode==='ocr'?'Дайын. Мәтінді тексеріп, Word немесе TXT жүкте.':'Дайын. Файл жүктеуге жіберілді.');
}catch(e){status(cancelled?'Өңдеу тоқтатылды.':e.name==='PasswordException'?'PDF құпиясөзбен қорғалған. Құлыптан босатылған көшірмесін таңда.':('Өңдеу орындалмады. '+(e.message||'Файлды тексеріп, қайта көр.')),true);}finally{if(worker){await worker.terminate();worker=null;}if(loading)await loading.destroy();busy=false;$('cancel').hidden=true;document.querySelectorAll('nav button,select,input').forEach(e=>e.disabled=false);$('convert').disabled=!file;}}
$('file').onchange=e=>choose(e.target.files[0]);document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$('convert').onclick=run;$('cancel').onclick=()=>{cancelled=true;status('Ағымдағы бет аяқталған соң тоқтайды…');};
$('drop').ondragover=e=>{e.preventDefault();$('drop').classList.add('drag');};$('drop').ondragleave=()=>$('drop').classList.remove('drag');$('drop').ondrop=e=>{e.preventDefault();$('drop').classList.remove('drag');choose(e.dataTransfer.files[0]);};
$('txt').onclick=()=>download(new Blob(['\ufeff'+$('text').value],{type:'text/plain;charset=utf-8'}),'txt');$('word').onclick=async()=>{try{if(!$('text').value.trim())throw Error('Мәтін бос.');$('word').disabled=true;const d=new Document({sections:[{children:$('text').value.split('\n').map(t=>new Paragraph({children:[new TextRun({text:t,font:'Arial',size:24})]}))}]});download(await Packer.toBlob(d),'docx');}catch(e){status(e.message,true);}finally{$('word').disabled=false;}};
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'configure_conversion',description:'Select the visible conversion mode; does not read or upload files.',inputSchema:{type:'object',properties:{mode:{type:'string',enum:['ocr','image','pdf']}},required:['mode'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>setMode(input.mode)})).catch(()=>{});}catch{}}
